inherit_from:
  - .rubocop-shared.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - 'spec/integration_spec.rb'
    - 'spec/**/*_integration_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive
