plugins:
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml
  - .rubocop-shared.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Naming/PredicatePrefix:
  Enabled: true
  AllowedMethods:
    - is_a?
    - has_preferred_network?
    - is_wifi_interface?
