#!/usr/bin/env ruby
#
# push_all  Pushes a branch and its tags to all remote repos.
#

BRANCH = ARGV[0] || 'master'
REMOTES = `git remote -v`.split("\n").map { |line| line.split.first}.sort.uniq

puts "Pushing branch #{BRANCH} to remote repos #{REMOTES}."

REMOTES.each { |remote| `git push --tags #{remote} #{BRANCH} `}
